services:
  - type: web
    name: canteen-management
    env: node
    buildCommand: |
      npm install
      npx prisma generate
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true 